excluded:
  - Carthage
  - Pods
  - .build

reporter: "xcode"

line_length:
  warning: 140

identifier_name:
  min_length: 2
  allowed_symbols: "_"

type_name:
  min_length: 3

trailing_whitespace:
  ignores_empty_lines: true
